# Generated by Django 3.2.9 on 2021-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='options',
            field=models.CharField(default='option1,option2,option3', max_length=512),
            preserve_default=False,
        ),
    ]
