# Generated by Django 3.2.9 on 2021-11-30 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bordaapp', '0004_auto_20211130_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
