# Generated by Django 3.2.9 on 2022-04-22 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bordaapp', '0006_post_answered_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='answered_users',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
